### ISSUE TITLE
Lodash Requirement.

### ISSUE THREAD

**Issue by webark** [ember-cli-deploy/ember-cli-deploy-plugin#11]
Why are are we requiring lodash when it isn't being used? Ran into this due to a failing build of `Cannot find module 'lodash-node'` which brought me here, but it looks like it's not even being used after it's required. Can we just remove that dependency?

**Comment by ghedamat** [comment]
good point @webark , sorry about that

you should not get the error if you `nombom` as we fixed the require in package.json

lodash got in when I was working on the color option support for logging but at first glance it doesn't seem needed anymore so I wonder if I left it in by accident when I squashed the commits.

I'll double check the code as soon as I have the chance and likely kill it
