### ISSUE TITLE
Plugin hooks don't works

### ISSUE THREAD

**Issue by villander** [ember-cli-deploy/ember-cli-deploy-plugin#20]
Hi guys, I'm creating a plugin to upload source maps to airbrake.

I installed the plugin using `npm link` on my web app. But when I run `ember deploy production` or `ember deploy production --verbose` my plugin is never executed

https://github.com/PayCertify/ember-cli-deploy-airbrake/tree/EN-548/create-plugin-airbrake

**Comment by lukemelia** [comment]
@villander Looks like your plugin's package.json file is missing a keyword to designate it as a ecd plugin. See "Identify the addon as a plugin" under http://ember-cli-deploy.com/docs/v1.0.x/creating-a-plugin/#the-anatomy-of-a-plugin

**Comment by villander** [comment]
thanks @lukemelia now it works, but I have another issue.

my machine

```
ember-cli: 3.3.0
node: 8.11.4
os: darwin x64
```

I'm trying read source maps read is always empty. the problem happens on `_readSourceMap` function - https://github.com/PayCertify/ember-cli-deploy-airbrake/blob/EN-548%2Fcreate-plugin-airbrake/index.js#L102

```
|    - Uploading sourcemaps to Airbrake
|    - Uploading sourcemap to Airbrake: version= name=https://my.paycertify.com/assets/auto-import-fastboot-e289ea484a4d8949ea84cb262a624452.js file=tmp/deploy-dist/assets/auto-import-fastboot-81f919f3d82c38703c7b0de8c4c4a874.map
|    - Uploading sourcemap to Airbrake: version= name=https://my.paycertify.com/assets/vendor-9a51012fdf0474b17c5760686fdd3586.js file=tmp/deploy-dist/assets/vendor-534fce18d47740d0e26096c68734a690.map
|    - Uploading sourcemap to Airbrake: version= name=https://my.paycertify.com/assets/web-app-053d567f210ca3099a95b2ad14d9aa8e.js file=tmp/deploy-dist/assets/web-app-12465c4e2bb0e4ec3979d1019af914cf.map
|
+- didFail
StatusCodeError: 400 - "{\"code\":400,\"type\":\"Bad Request\",\"message\":\"sourcemap: mappings are empty\"}"
StatusCodeError: 400 - "{\"code\":400,\"type\":\"Bad Request\",\"message\":\"sourcemap: mappings are empty\"}"
```
is there anything related to the read permission or something. Almost ember-cli deploy plugins use this function and it seems to work fine, but in my case it does not work

**Comment by achambers** [comment]
Hi @villander. I’m looking at your plugin on my phone so excuse any daft questions. 

Can you let me know what the value of `mapFilePath`, `relativeMapFilePath` and `gzippedFiles` is please?
