### ISSUE TITLE
No repository field

### ISSUE THREAD

**Issue by broerse** [ember-cli-deploy/ember-cli-deploy-plugin#4]
`npm WARN package.json ember-cli-deploy-couchdb@0.0.0 No repository field.`

**Comment by achambers** [comment]
Hi @broerse. Are you sure you have correct repo here?

**Comment by broerse** [comment]
I did `npm install ember-cli-deploy-plugin --save` and got `"ember-cli-deploy-plugin": "^0.2.0"` 

https://github.com/broerse/ember-cli-deploy-couchdb/blob/master/package.json

It gives me the warning.

ember-cli-deploy-couchdb\node_modules\ember-cli-deploy-plugin\package.json

```
{
  "name": "ember-cli-deploy-plugin",
  "version": "0.2.0",
  "description": "For building plugins for ember-cli-deploy",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ember-cli-deploy/ember-cli-deploy-plugin.git"
  },
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": {
    "name": "Luke Melia and ember-cli-deploy team"
  },
  "license": "MIT",
  "devDependencies": {},
  "dependencies": {
    "chalk": "^1.0.0",
    "core-object": "0.0.2"
  },
  "gitHead": "efee3cb7e59e368a48163fc8b9a32a7c209e74a8",
```

**Comment by lukemelia** [comment]
@broerse I'm not seeing this in any of our projects. Going to close for now. Feel free to reopen with reproduction steps.

**Comment by broerse** [comment]
Just tried to reproduce it but can't. Will report back if I see it again.
