### ISSUE TITLE
Can't list or activate revisions

### ISSUE THREAD

**Issue by jrdn91** [ember-cli-deploy/ember-cli-deploy-plugin#5]
Each time I try to run `ember deploy:list` or `ember deploy:activate --revision ***` I get `You need to provide a deployTarget: 'ember deploy production'`

**Comment by lukemelia** [comment]
@Jordan4jc you have to run something like `ember deploy:list production` or `ember deploy:activate production --revision ***` where `production` is one of your deployTargets.

**Comment by jrdn91** [comment]
That's what I thought, maybe I'm anticipating something wrong here but when I run `ember deploy:list production` nothing lists, shouldn't it list revisions that have been deployed that I can activate?

**Comment by lukemelia** [comment]
Your expectation is correct. Two things: 1) Is `production` the name of your deploymentTarget? 2) This issue should be opened on the plugin that is being used to upload/activate your index.html (ember-cli-deploy-s3-index in your case I believe.)
